### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by Ayush5120**
1. Added exceptions for tasks not found in  `GET /tasks/{id}` endpoint.
2. Removed unnecessary config files.

### CODE REVIEW

**Comment by uniqueg** [comment]
Removing config handler is now addressed here: https://github.com/elixir-cloud-aai/proTES/pull/100

**Review by uniqueg — CHANGES_REQUESTED** [review]
Additional errors look like a good thing, but it seems to me that (1) `EngineProblem` should also show up in the exceptions dictionary and (2) these errors should actually be used somewhere in the code?

Re: removal of config parser, see other message (basically, this is already taken care of in another PR)

**Comment by Ayush5120** [comment]
> Additional errors look like a good thing, but it seems to me that (1) `EngineProblem` should also show up in the exceptions dictionary and (2) these errors should actually be used somewhere in the code?
> 
> Re: removal of config parser, see other message (basically, this is already taken care of in another PR)

Ok I will add `EngineProblem ` as stated and (2) Yeah I do found that most of the errors are defined and never used I will fix them in next commit.

**Comment by uniqueg** [comment]
I'm not sure if this PR is still needed after refactoring proTES in November. Can you please check @Ayush5120, and either update or close the PR? :pray:

**Comment by Ayush5120** [comment]
Yes @uniqueg you are right, this was handled in the pr [#114](https://github.com/elixir-cloud-aai/proTES/pull/114). Hence closing this PR.

**Pull request closed without merging**
