### PR TITLE
feat: update TES models to v1.1

### PR DESCRIPTION
**Pull request by athith-g**
**Details**

Added fields that were added in TES v1.1 to `models.py`

[TES v1.1 changes:](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1)
- [x] Proposal: add "backend_parameters" to tesResources
- Added [here](https://github.com/elixir-cloud-aai/proTES/commit/c04cbab851202f4cc9752561703985880148e526)
- [x] Add in new tesState for preempted state
- Added [here](https://github.com/elixir-cloud-aai/proTES/commit/edb2f75404afa52726abbf6406e9e2bfdbd54780)
- [ ] feat: allow wildcards in output paths
- **NOT** added. It seems like this is being reverted in https://github.com/ga4gh/task-execution-schemas/pull/195
- [x] Making file type an optional argument
- Added [here](https://github.com/elixir-cloud-aai/proTES/commit/d5e059cdd96f1ee065379bce9e91ae3a75263643)
- [ ] Changing int64 to int32 for page_size and cpu_count
- Not in `models.py`
- [x] Adding ignore_error flag
- Added [here](https://github.com/elixir-cloud-aai/proTES/commit/25edbb64d12ba541d58e821c21f374013cc1ec76)
- [x] Add CANCELING state to delete cloud resources 
- Added [here](https://github.com/elixir-cloud-aai/proTES/commit/edb2f75404afa52726abbf6406e9e2bfdbd54780)
- [x] Adding streamable flag to tesInput
- Added [here](https://github.com/elixir-cloud-aai/proTES/commit/24c511e93fc313893ff72ca4fde6178a6443c788)
- [ ] Adding filtering features to task listing
- Not in `models.py`

I removed the unnecessary newlines but I'm not sure how to achieve the whitespacing in the existing descriptions.

## Summary by Sourcery

Updated TES models to v1.1 by adding new fields and states to support the latest features and configurations as per the TES v1.1 specification.

- **New Features**:
    - Added 'ignore_error' field to TesExecutor to allow continuation on errors.
    - Made 'type' field in TesInput and TesOutput optional with a default value of 'FILE'.
    - Added 'streamable' flag to TesInput to indicate potential use of streaming interfaces.
    - Introduced 'backend_parameters' and 'backend_parameters_strict' fields to TesResources for backend configuration.
    - Added 'PREEMPTED' and 'CANCELING' states to TesState.

### CODE REVIEW

**Review by uniqueg — COMMENTED** [review]
Looks good to me. However, the one open Sourcery AI comment looks reasonable - although I have no clue if their suggested change works. Maybe you can try it out and either replace or comment on why it didn't work

**Comment by uniqueg** [comment]
Also - tests fail...

**Comment by athith-g** [comment]
I think the rest of the linting and integration tests will pass once #178 is merged.

**Review by uniqueg — APPROVED** [review]

**Comment by uniqueg** [comment]
LGTM, @athith-g - I think you can merge :)

**Pull request merged**
